embed_path: data/emb/ICLR/2023/20250605_1153
data_path: data/unified_text/ICLR/ICLR_2023.json
output_path: result/ICLR/2023/
models:
  - GreedyCohesive
  - KMeans
  - KMedoids
  - Baseline
k: 0 # Default, match baselines
metric: 'euclidean'
# TODO: implement eval fine-grained control

# Visualize
visualize: True
# TODO: two more dirs are annoying.
metadata: data/metadata/ICLR/2023.csv
paper_dir: result/ICLR/2023/papers/
methods:
  - umap
  - tsne
  - pca
n_components: 2
perplexity: 30
random_state: 42