embed_path: data/emb/ICLR/2024/20250530_1457/
data_path: data/unified_text/ICLR/ICLR_2024.json
output_path: result/ICLR/2024/
models:
  - GreedyCohesive
  - KMeans
  - KMedoids
  - Baseline # Our u
k: 0 # Default, match baselines
metric: 'euclidean'
# TODO: implement eval fine-grained control