embed_path: data/emb/NeurIPS/2023/20250602_2201
data_path: data/unified_text/NeurIPS/NeurIPS_2023.json
output_path: result/NeurIPS/2023/
models:
  - GreedyCohesive
  - KMeans
  - KMedoids
  - Baseline
k: 0 # Default, match baselines
metric: 'euclidean'
# TODO: implement eval fine-grained control