embed_path: data/emb/NeurIPS/2024/20250530_1451
data_path: data/unified_text/NeurIPS/NeurIPS_2024.json
output_path: result/NeurIPS/2024/
models:
  - GreedyCohesive
  - KMeans
  - KMedoids
  - Baseline
k: 0 # Default, match baselines
metric: 'euclidean'
# TODO: implement eval fine-grained control