embed_path: data/emb/ICLR/2024/20250611_0009
metadata: data/metadata/ICLR/2024.csv
output_path: result/ICLR/2024/
models:
  - GreedyCohesive
  - KMeans
  - KMedoids
  - Baseline
k: 0 # Default, match baselines
metric: 'euclidean'
# TODO: implement eval fine-grained control

# Visualize
visualize: True
paper_dir: # default to <output_path>/papers/
methods:
  - umap
  - tsne
  - pca
n_components: 2
perplexity: 30
random_state: 42