model: text-embedding-004
provider: gemini # Choose from openai, anthropic, sent_trans for SentenceTransformer compatible models
input_json: data/unified_text/ICLR/ICLR_2024.json
output_folder: data/emb/ICLR/2024/
include: # Options: year, authors, title, abstract, text, publisher, session, forum_content
  - title
  - authors
  - abstract
exclude: []
stride: 4000
max_tokens: 0 # Default to model's max tokens
verbose: True
