model: text-embedding-3-large
input_path: src/tmp.json
output_path: data/emb/NeurIPS/2023/
include: # Options: year, authors, title, abstract, text, publisher, session, forum_content
  - title
  - authors
  - abstract
  - text
exclude: []
stride: 1000
max_tokens: 0 # Default to model's max tokens
verbose: True
