model: text-embedding-3-large
provider: openai # Choose from openai, anthropic, sent_trans for SentenceTransformer compatible models
input_json: data/unified_text/ICLR/ICLR_2021.json
output_folder: data/emb/ICLR/2021/
include: # Options: year, authors, title, abstract, text, publisher, session, forum_content
  - title
  - authors
  - abstract
  - text
exclude: []
stride: 1000
max_tokens: 0 # Default to model's max tokens
verbose: True
